# Laptop-specific config

exec-once = waypaper --restore --folder ~/Pictures/Backgrounds

# Simple monitor setup
monitor=,preferred,auto,1

# Basic workspace setup (no specific monitor assignments needed)
workspace = 1, name:web
workspace = 2, name:main
workspace = 3, name:dev
workspace = 4, name:chat
workspace = 5, name:media
workspace = 10, name:games

input {
    sensitivity = 0.25

    touchpad {
        natural_scroll = true
        tap-to-click = true
        drag_lock = true
        disable_while_typing = true
        #middle_button_emulation = true
    }
}

gestures {
    workspace_swipe = true
}